[package]
name = "fourhills"
version = "0.1.0"
authors = ["Michael Hart <michael.hart1994@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.10.0"
stdweb = "0.4.20"
